# Generated by Django 3.2.5 on 2021-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedValueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('derscription', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='home/', verbose_name='Image')),
                ('button_toggle', models.BooleanField(default=True, verbose_name='Button Toggle')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField(verbose_name='Link')),
                ('value1', models.CharField(blank=True, max_length=100, null=True)),
                ('value2', models.CharField(blank=True, max_length=100, null=True)),
                ('value3', models.CharField(blank=True, max_length=100, null=True)),
                ('value4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('derscription', models.TextField(verbose_name='Description')),
                ('button_toggle', models.BooleanField(default=True, verbose_name='Button Toggle')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField(verbose_name='Link')),
                ('value1', models.CharField(blank=True, max_length=100, null=True)),
                ('value2', models.CharField(blank=True, max_length=100, null=True)),
                ('value3', models.CharField(blank=True, max_length=100, null=True)),
                ('value4', models.CharField(blank=True, max_length=100, null=True)),
                ('feature1_title', models.CharField(max_length=100)),
                ('feature1_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('feature1_description', models.TextField(verbose_name='Description')),
                ('feature2_title', models.CharField(max_length=100)),
                ('feature2_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('feature2_description', models.TextField(verbose_name='Description')),
                ('feature3_title', models.CharField(max_length=100)),
                ('feature3_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('feature3_description', models.TextField(verbose_name='Description')),
                ('feature4_title', models.CharField(max_length=100)),
                ('feature4_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('feature4_description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=22)),
                ('youtube_link', models.URLField(verbose_name='Youtube Link')),
                ('facebook_link', models.URLField(verbose_name='facebook Link')),
                ('twitter_link', models.URLField(verbose_name='twitter Link')),
                ('about_company', models.TextField(verbose_name='About Company')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('derscription', models.TextField(verbose_name='Description')),
                ('button_toggle', models.BooleanField(default=True, verbose_name='Button Toggle')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField(verbose_name='Link')),
                ('image', models.ImageField(upload_to='feature/', verbose_name='Image')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('banner', models.BooleanField(default=False, verbose_name='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
                ('button_toggle', models.BooleanField(default=True, verbose_name='Button Toggle')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField(verbose_name='Link')),
                ('image', models.ImageField(upload_to='home/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('review', models.TextField(verbose_name='Review')),
                ('image', models.ImageField(upload_to='home/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('derscription', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='home/', verbose_name='Image')),
                ('statics1_title', models.CharField(max_length=100)),
                ('statics1_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('statics1_number', models.IntegerField(verbose_name='Statics 1 Number')),
                ('statics2_title', models.CharField(max_length=100)),
                ('statics2_icon', models.ImageField(upload_to='benefit/', verbose_name='Image')),
                ('statics2_number', models.IntegerField(verbose_name='Statics 1 Number')),
            ],
        ),
        migrations.CreateModel(
            name='SubFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='feature/', verbose_name='Image')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='SubFeatureHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('sub_features', models.ManyToManyField(to='website.SubFeatures', verbose_name='Sub Features')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReviewTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('reviews', models.ManyToManyField(to='website.Review', verbose_name='Review')),
            ],
        ),
        migrations.CreateModel(
            name='CoreFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitle')),
                ('features', models.ManyToManyField(to='website.Feature', verbose_name='Features')),
            ],
        ),
    ]
