# Generated by Django 3.2.5 on 2021-10-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('mobile_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_client', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End Date')),
                ('attachment', models.FileField(upload_to='projects/', verbose_name='Attachment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='managers.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_project', to='settings.company')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_user', to=settings.AUTH_USER_MODEL, verbose_name='Leader')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('piriority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pirority', to='settings.projectperiority', verbose_name='Perioirty')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='settings.projectstatus', verbose_name='Status')),
                ('team', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='managers.project', verbose_name='Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='settings.taskstatus', verbose_name='Status')),
            ],
        ),
    ]
