# Generated by Django 3.2.5 on 2021-10-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('managers', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservacationrequest',
            name='vacation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vacation_type', to='settings.vacationtype', verbose_name='vacation type'),
        ),
        migrations.AddField(
            model_name='usertravel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_travel_city', to='settings.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='usertravel',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket_type', to='settings.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.AddField(
            model_name='usertravel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_travel', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_course', to='settings.trainingcourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='training_employee', to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
        migrations.AddField(
            model_name='usertermination',
            name='termination_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_terminate_reason', to='settings.reasontoterminate', verbose_name='Termination Type'),
        ),
        migrations.AddField(
            model_name='usertermination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_termination', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usersocialinsurance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_insurance', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usersalary',
            name='attendence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendence_type', to='settings.attendencetype', verbose_name='Attendence Type'),
        ),
        migrations.AddField(
            model_name='usersalary',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bankname', verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='usersalary',
            name='salary_pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_salary_pay_type', to='settings.salarypaytype', verbose_name='Salary Pay Type'),
        ),
        migrations.AddField(
            model_name='usersalary',
            name='salary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_salary_type', to='settings.salarytype', verbose_name='salary type'),
        ),
        migrations.AddField(
            model_name='usersalary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_salary', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userresign',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resign_reason', to='settings.reasontoresign'),
        ),
        migrations.AddField(
            model_name='userresign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resign_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userreplacements',
            name='replacement_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uer_replacement_period', to='settings.replacementperiod', verbose_name='Replacement For'),
        ),
        migrations.AddField(
            model_name='userreplacements',
            name='replacement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replacement_type', to='settings.replacementtype', verbose_name='repacement type'),
        ),
        migrations.AddField(
            model_name='userreplacements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replacements', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='from_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_grade', to='settings.jobgrade'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='from_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_type', to='settings.jobtype'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='to_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_grade', to='settings.jobgrade'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='to_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_type', to='settings.jobtype'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='settings.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userperformanceindicator',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_performance_indicator', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='userovertime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usermedicalinsurance',
            name='insurance_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_class', to='settings.insuranceclass', verbose_name='Insurance Class'),
        ),
        migrations.AddField(
            model_name='usermedicalinsurance',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_company', to='settings.insurancecompany', verbose_name='Insurance Company'),
        ),
        migrations.AddField(
            model_name='usermedicalinsurance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_medical_attachments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_branch', to='settings.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='department_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_manager', to=settings.AUTH_USER_MODEL, verbose_name='Department Manager'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='department_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department_section', to='settings.department_section', verbose_name='Department or Section'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='direct_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to=settings.AUTH_USER_MODEL, verbose_name='Direct Manager'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='employee_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_status', to='settings.employeestatus', verbose_name='Employee Status'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_grade', to='settings.jobgrade', verbose_name='Job Grade'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_job_type', to='settings.jobtype', verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='project_or_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to='managers.project', verbose_name='user project'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='settings.qualifications', verbose_name='user qualifications'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userfollowers',
            name='follower_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower_Type', to='settings.followertype'),
        ),
        migrations.AddField(
            model_name='userfollowers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userevaluation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_evaluation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdiscounts',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount_type', to='settings.discounttype', verbose_name='repacement type'),
        ),
        migrations.AddField(
            model_name='userdiscounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usercontract',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_contract', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userassets',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset', to='settings.assets'),
        ),
        migrations.AddField(
            model_name='userassets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset_status', to='settings.assetstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='userassets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rassets_equests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='useraccountsconnection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='settings.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='useraccountsconnection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='leave_reasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leave_resons', to='settings.leavereasons', verbose_name='Leave Reasons'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loan_type', to='settings.loantype', verbose_name='Loan Type'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
