# Generated by Django 3.2.5 on 2021-10-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='job_title',
            field=models.CharField(default='', max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='usermedicalinsurance',
            name='insurance_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_class', to='settings.insuranceclass', verbose_name='Insurance Class'),
        ),
        migrations.AlterField(
            model_name='usermedicalinsurance',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_company', to='settings.insurancecompany', verbose_name='Insurance Company'),
        ),
        migrations.AlterField(
            model_name='usermedicalinsurance',
            name='insurance_number',
            field=models.IntegerField(default=0, verbose_name='Insurance Number'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='attendence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attendence_type', to='settings.attendencetype', verbose_name='Attendence Type'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='bank_account_iban',
            field=models.CharField(default='', max_length=25, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='bank_account_number',
            field=models.IntegerField(default='', verbose_name='bank account number'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.bankname', verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='daily_working_hours',
            field=models.FloatField(default=0, verbose_name='Daily Working Hours'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='main_salary',
            field=models.FloatField(default=0, verbose_name='Main Salary'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='net_salary',
            field=models.FloatField(default=0, verbose_name='Net Salary'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='salary_pay_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_salary_pay_type', to='settings.salarypaytype', verbose_name='Salary Pay Type'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='salary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_salary_type', to='settings.salarytype', verbose_name='salary type'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='stop_reason',
            field=models.TextField(default='', max_length=50, verbose_name='Stop Reason'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='yearly_vacation_days_count',
            field=models.IntegerField(default=0, verbose_name='Yearly Vacations Days'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='basic_salary',
            field=models.FloatField(default=0, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='comissions_replacement',
            field=models.FloatField(default=0, verbose_name='Comission Replacement'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='housing_replacement',
            field=models.FloatField(default=0, verbose_name='Housing Replacement'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='labrorary_office_number',
            field=models.IntegerField(default=0, verbose_name='Labrorary Office Number'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='other_replacements',
            field=models.FloatField(default=0, verbose_name='Other Replacements'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='salary_under_social_insurance',
            field=models.FloatField(default=0, verbose_name='Salary Under Social Insurance'),
        ),
        migrations.AlterField(
            model_name='usersocialinsurance',
            name='social_insurance_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Social Insurance Id'),
        ),
    ]
