# Generated by Django 3.2.5 on 2021-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211020_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_location',
            field=models.CharField(default='', max_length=100, verbose_name='Birth Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_issue_location',
            field=models.CharField(default='', max_length=100, verbose_name='Id Issue Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Id Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='', max_length=100, verbose_name='Job as In Id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(default='', max_length=15, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('MUSLIM', 'MUSLIM'), ('CHRISTIEN', 'CHRISTIEN'), ('OTHER', 'OTHER')], default='MUSLIM', max_length=50, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='bank_account_number',
            field=models.IntegerField(default=0, verbose_name='bank account number'),
        ),
    ]
