# Generated by Django 3.2.5 on 2021-10-23 11:25

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211023_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreplacements',
            name='month',
            field=month.models.MonthField(blank=True, null=True),
        ),
    ]
