# Generated by Django 3.2.5 on 2021-10-23 11:26

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userreplacements_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userovertime',
            name='month',
            field=month.models.MonthField(blank=True, null=True),
        ),
    ]
