# Generated by Django 3.2.5 on 2021-10-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('fax_number', models.CharField(max_length=20, verbose_name='Fax Number')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website Url')),
                ('website_name', models.CharField(default='', max_length=100, verbose_name='Website Name')),
                ('logo', models.ImageField(default='', upload_to='logo/', verbose_name='Logo')),
                ('fav_icon', models.ImageField(default='', upload_to='icon/', verbose_name='Fav Icon')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.city', verbose_name='city')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_user', to=settings.AUTH_USER_MODEL, verbose_name='Contact Person')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_department_section', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_in_over_time', models.FloatField(verbose_name='Hour In Over Time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_working_hourse', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_vacation_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN ACTIVE', 'IN ACTIVE')], max_length=15, verbose_name='status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_training_course', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ticket_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_task_status', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_salary_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_salary_pay_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_request_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_replacement_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_replacement_period', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonToTerminate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reasons_to_terminate', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonToResign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reasons_to_resign', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_qualifications', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_project_status', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPeriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_project_periority', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='Description')),
                ('upload_policy', models.FileField(upload_to='policy/', verbose_name='Upload Policy')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_organization_policies', to='settings.company')),
                ('department_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_department_section', to='settings.department_section', verbose_name='Department or section')),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_loan_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leave_reasons', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job_type', to='settings.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_department', to='settings.department_section', verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job_grade', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_insurance_company', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_insurance_class', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='Date From')),
                ('date_to', models.DateField(default=django.utils.timezone.now, verbose_name='Date From')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_holiday', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_follower_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee_status', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_discount_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='Default Password')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_default_password', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyThemeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50, verbose_name='Website Name')),
                ('logo', models.ImageField(upload_to='company_logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(upload_to='company_icon', verbose_name='FavIcon')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_city', to='settings.city', verbose_name='city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branch', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_name', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_attendance_type', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_asset_status', to='settings.company')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('asset_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Asset')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date')),
                ('warranty', models.CharField(max_length=12, verbose_name='Warrnty')),
                ('warranty_end', models.DateField(default=django.utils.timezone.now, verbose_name='Warranty End Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('supplier', models.CharField(max_length=50, verbose_name='Supplier')),
                ('manufacture', models.CharField(max_length=50, verbose_name='manufacture')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_asset', to='settings.company')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_contion', to='settings.assetcondition', verbose_name='Condition')),
            ],
        ),
        migrations.AddField(
            model_name='assetcondition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_asset_condition', to='settings.company'),
        ),
        migrations.CreateModel(
            name='AnnualVacationDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_annual_vations', to='settings.company')),
            ],
        ),
    ]
