# Generated by Django 3.2.5 on 2021-10-20 09:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_number',
            field=models.CharField(default='', max_length=20, verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(default='', max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name='Postal Code'),
        ),
    ]
